WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM dba_users
    WHERE username = 'COBBLEUSER';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER COBBLEUSER IDENTIFIED BY "Oracle#12345@"';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER COBBLEUSER IDENTIFIED BY "Oracle#12345@" ACCOUNT UNLOCK';
    END IF;
END;
/

GRANT CONNECT, RESOURCE TO COBBLEUSER;
ALTER USER COBBLEUSER QUOTA UNLIMITED ON USERS;

EXIT
